# Generated by Django 5.1.2 on 2024-12-05 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_client_description_client_profile_picture'),
        ('main', '0002_load_sample_data'),
    ]

    operations = [
    ]
